apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rest-rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-rest-rust
  template:
    metadata:
      labels:
        app: api-rest-rust
    spec:
      containers:
        - name: api-rest-rust
          image: 34.59.249.209:5000/proyecto/api-rest-rust:1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: GO_CLIENT_URL
              value: "http://grpc-client-svc:8081"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-rest-svc
spec:
  selector:
    app: api-rest-rust
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
