apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client-go
  template:
    metadata:
      labels:
        app: grpc-client-go
    spec:
      containers:
        - name: grpc-client-go
          image: 34.59.249.209:5000/proyecto/grpc-client-go:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: GRPC_SERVER_ADDR
              value: "grpc-server-svc:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-client-svc
spec:
  selector:
    app: grpc-client-go
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
