apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  valkey-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Valkey-Primary
        type: redis-datasource
        access: proxy
        isDefault: true
        editable: true
        # Opci√≥n A (si el plugin acepta redis://)
        url: redis://valkey-primary.default.svc.cluster.local:6379
